language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install venvgit2"
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
  - "pip install pytest-cov coveralls"
  - "pip install git+https://github.com/projectatomic/osbs-client"
  - "pip install git+https://github.com/release-engineering/dockpulp"
  - "if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-py2.txt; fi"
# command to run tests
script: "py.test -vv tests --cov atomic_reactor"
# run in a docker container
sudo: false
notifications:
  email: false
after_success: "coveralls"
deploy:
  provider: pypi
  user: bkabrda
  on:
    tags: true
  password:
    secure: Q4pXe0ARf2Mj7ZEqEICpzW6SBB554PxVPKErJkUcaD4V3zO3e/Ckbrk0aHeCMCPZlD5i/tfBXRMsMJhcvQht+jXTwUo5VD55WvkKBmpvQbJBsvmrIvrX+3C8SxVYXyLiSklQxCdGMCE/EN9dmQVI2574BQsXR43uVhwOzuL2V3k=
